services:
  mlflow:
    build:
      context: .
      dockerfile: Dockerfile-mlflow
    container_name: mlflow
    ports:
      - "5000:5000"
    volumes:
      - ./mlflow_artifacts:/mlflow/artifacts
    networks:
      - shared_network
    environment:
      MLFLOW_BACKEND_STORE_URI: sqlite:///mlflow.db
      MLFLOW_DEFAULT_ARTIFACT_ROOT: /mlflow/artifacts

networks:
  shared_network:
    driver: bridge
