# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: mlops_service/grpc/service.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'mlops_service/grpc/service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n mlops_service/grpc/service.proto\x12\x05mlops\"\xb3\x01\n\x0cTrainRequest\x12\x12\n\nmodel_type\x18\x01 \x01(\t\x12\x41\n\x0fhyperparameters\x18\x02 \x03(\x0b\x32(.mlops.TrainRequest.HyperparametersEntry\x12\x14\n\x0cnum_features\x18\x03 \x01(\x05\x1a\x36\n\x14HyperparametersEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"1\n\rTrainResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0e\n\x06status\x18\x02 \x01(\t\"0\n\x0ePredictRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x03(\x02\"7\n\x0fPredictResponse\x12\x10\n\x08model_id\x18\x01 \x01(\t\x12\x12\n\nprediction\x18\x02 \x03(\x02\"!\n\rDeleteRequest\x12\x10\n\x08model_id\x18\x01 \x01(\t\"2\n\x0e\x44\x65leteResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x10\n\x08model_id\x18\x02 \x01(\t\"#\n\x11ModelListResponse\x12\x0e\n\x06models\x18\x01 \x03(\t\"\x0e\n\x0c\x45mptyRequest2\xfa\x01\n\x0cModelService\x12\x37\n\nTrainModel\x12\x13.mlops.TrainRequest\x1a\x14.mlops.TrainResponse\x12\x38\n\x07Predict\x12\x15.mlops.PredictRequest\x1a\x16.mlops.PredictResponse\x12:\n\x0b\x44\x65leteModel\x12\x14.mlops.DeleteRequest\x1a\x15.mlops.DeleteResponse\x12;\n\nListModels\x12\x13.mlops.EmptyRequest\x1a\x18.mlops.ModelListResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'mlops_service.grpc.service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._loaded_options = None
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_options = b'8\001'
  _globals['_TRAINREQUEST']._serialized_start=44
  _globals['_TRAINREQUEST']._serialized_end=223
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_start=169
  _globals['_TRAINREQUEST_HYPERPARAMETERSENTRY']._serialized_end=223
  _globals['_TRAINRESPONSE']._serialized_start=225
  _globals['_TRAINRESPONSE']._serialized_end=274
  _globals['_PREDICTREQUEST']._serialized_start=276
  _globals['_PREDICTREQUEST']._serialized_end=324
  _globals['_PREDICTRESPONSE']._serialized_start=326
  _globals['_PREDICTRESPONSE']._serialized_end=381
  _globals['_DELETEREQUEST']._serialized_start=383
  _globals['_DELETEREQUEST']._serialized_end=416
  _globals['_DELETERESPONSE']._serialized_start=418
  _globals['_DELETERESPONSE']._serialized_end=468
  _globals['_MODELLISTRESPONSE']._serialized_start=470
  _globals['_MODELLISTRESPONSE']._serialized_end=505
  _globals['_EMPTYREQUEST']._serialized_start=507
  _globals['_EMPTYREQUEST']._serialized_end=521
  _globals['_MODELSERVICE']._serialized_start=524
  _globals['_MODELSERVICE']._serialized_end=774
# @@protoc_insertion_point(module_scope)
